alias ls="exa --icons"
alias ll="exa -lbF --icons --git"
alias llm="exa -lbF --icons --git --sort=modified"
alias la="exa -lbhHigUmuSa --icons --git --color-scale --time-style=long-iso"
alias laa="exa -lbhHigUmuSaa --icons --git --color-scale --time-style=long-iso"
alias lx="exa -lbhHigUmuSa@ --icons --git --color-scale --time-style=long-iso"
alias lxa="exa -lbhHigUmuSa@a --icons --git --color-scale --time-style=long-iso"
alias lS="exa -1"
alias llt="exa -1 --icons --tree --git"
alias llta="exa -1 --icons --tree --git --all"
