#!/usr/bin/env bash

brew_path=$(which brew)
if [ -x "$brew_path" ] ; then
  echo "Install/Updating Homebrew Packages"
  echo ""
else
  echo "Installing homebrew"
  echo ""
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  if [ $? -ne 0 ]; then
    echo "Error installing homebrew. Bailing..."
    echo ""
    exit 1;
  else
    brew doctor
    if [ $? -ne 0 ]; then
      echo "Brew Doctor is not happy. Bailing..."
      echo ""
      exit 1;
    fi
  fi
fi

brew update

brew upgrade

brew install ack
brew install ag
brew install ansible
brew install apple-gcc42
brew install boot2docker
brew install chruby
brew install coreutils
brew install docker
brew install elixir
brew install fig
brew install gdbm
brew install git
brew install git-flow
brew install go
brew install gnupg2
brew install heroku-toolbelt
brew install htop-osx
brew install hub
brew install imagemagick
brew install leiningen
brew install libffi
brew install libyaml
brew install macvim --override-system-vim
brew install maven
brew install ngrok
brew install openssl
brew install readline
brew install reattach-to-user-namespace
brew install ruby-install
brew install sbt
brew install scala
brew install tmux
brew install ttyrec
brew install typesafe-activator
brew install unixodbc
brew install weechat --with-python --with-ruby --with-aspell

brew install https://raw.github.com/falsecz/homebrew-misc/master/Formula/git-wtf.rb

# At the end, because they require user intervention
brew install mongodb
brew install postgresql
brew install redis

brew cleanup
