#!/usr/bin/env bash

brew_path=$(which brew)
if [ -x "$brew_path" ] ; then
  echo "Install/Updating Homebrew Packages"
  echo ""

  #brew tap caskroom/cask
  #brew tap caskroom/versions
  #brew install brew-cask

  function installcask() {
    brew cask install "${@}"
  }

  installcask java8

  installcask 1password
  installcask adobe-creative-cloud
  installcask alfred
  installcask anki
  installcask arq
  installcask bartender
  installcask bettertouchtool
  installcask burp-suite
  installcask daisydisk
  installcask dash
  installcask discord
  installcask docker
  installcask dropbox
  installcask firefox
  installcask fluid
  installcask google-chrome
  installcask handbrake
  installcask handbrakecli
  installcask hazel
  installcask hyper-canary
  installcask imazing
  installcask istat-menus
  installcask iterm2
  installcask keycastr
  installcask microsoft-office
  installcask moom
  installcask nextcloud
  installcask ngrok
  installcask phantomjs
  installcask postman
  installcask robo-3t
  installcask rowanj-gitx
  installcask secure-pipes
  installcask sequel-pro
  installcask shimo
  installcask skype
  installcask slack
  installcask spotify
  installcask superduper
  installcask teamviewer
  installcask virtualbox
  installcask virtualbox-extension-pack
  installcask visual-studio-code
  installcask vlc
  installcask whatsapp
  installcask zoomus
else
  echo "Install Homebrew first. Run ~/dotfiles/brew first."
  echo ""
fi
