#!/usr/bin/env bash

brew_path=$(which brew)
if [ -x "$brew_path" ] ; then
  echo "Install/Updating Homebrew Packages"
  echo ""

  brew tap caskroom/homebrew-cask
  brew install brew-cask

  function installcask() {
    brew cask install "${@}"
  }

  installcask adobe-creative-cloud
  installcask alfred
  installcask atom
  installcask crashplan
  installcask dbvisualizer
  installcask docker-toolbox
  installcask dropbox
  installcask gitter
  installcask gitup
  installcask gitx-rowanj
  installcask google-chrome
  installcask google-earth
  installcask gopro-studio
  installcask handbrake
  installcask handbrakecli
  installcask intellij-idea
  installcask iterm2
  installcask istat-menus
  installcask java
  installcask mactex
  installcask makemkv
  installcask sharemouse
  installcask sidestep
  installcask skype
  installcask slack
  installcask sourcetree
  installcask spotify
  installcask steam
  installcask teamviewer
  installcask vagrant
  installcask virtualbox
  installcask vlc
else
  echo "Install Homebrew first. Run ~/dotfiles/brew first."
  echo ""
fi
