#!/bin/bash

cd $HOME

# What are we packing?
system_type=$(uname -s)

# Because submodules suck...
git clone https://github.com/gpakosz/.tmux.git $HOME/.tmux
mkdir -p $HOME/.config
git clone git@github.com:tedkulp/lazyvim $HOME/.config/nvim

# Link in our tmux config
if [ ! -f "$HOME/.tmux.conf" ]; then
	ln -s -f .tmux/.tmux.conf
fi

# Wrapping up
echo "Don't forget to run yadm decrypt!"
exit 0
