#!/bin/bash

cd $HOME 

# What are we packing?
system_type=$(uname -s)

# Install submodules
echo "Init submodules"
yadm submodule update --recursive --init

# Link in our tmux config
if [ ! -f "$HOME/.tmux.conf" ]; then
  ln -s -f .tmux/.tmux.conf
fi

# Wrapping up
echo "Don't forget to run yadm decrypt!"
exit 0
