#!/bin/bash

cd $HOME 

echo "Init submodules"
yadm submodule update --recursive --init

if [ ! -f "$HOME/.tmux.conf" ]; then
  ln -s -f .tmux/.tmux.conf
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

