alias ls="eza --icons"
alias ll="eza -lbF --icons --git"
alias llm="ll --sort=modified"
alias la="eza -lbhHigUmuSa --icons --git --color-scale --time-style=long-iso"
alias lam="la --sort=modified"
alias laa="eza -lbhHigUmuSaa --icons --git --color-scale --time-style=long-iso"
alias lx="eza -lbhHigUmuSa@ --icons --git --color-scale --time-style=long-iso"
alias lxa="eza -lbhHigUmuSa@a --icons --git --color-scale --time-style=long-iso"
alias lS="eza -1"
alias llt="eza -1 --icons --tree --git"
alias llta="eza -1 --icons --tree --git --all"
